### ISSUE TITLE
Lower chances to missconfigure the csaf_provider

### ISSUE THREAD

**Issue by bernhardreiter** [csaf-poc/csaf_distribution#178]
For v0.9.1 it is possible to have something like

```toml
[provider_metadata]
  list_on_CSAF_aggregators = false
  mirror_on_CSAF_aggregators = false
  publisher = {"category"= "vendor", "name"= "Example2", "namespace"= "https://2.example.com"}

upload_limit = 5
```

which is missleading because `upload_limit` will now be part of provider_metadata and thus _not_ be active.
This is a security problem, when done with `issuer`.

#### considerations
* Would help to change the order in the config option documentation (as tables must come last in TOML).
* If #152 can be implemented, it would also help
* An alternative to #152 could be to have a full example in the documentation and to mention the issue.
